services:
   php:
      build:
         context: .
         dockerfile: Dockerfile

      container_name: ecommerce_php

      ports:
         - "8080:80"

      volumes:
         - .:/var/www/html

      env_file:
         - .env

      restart: unless-stopped
